'use client';
import { useEffect, useState } from 'react';
type Report = { stats: Record<string, number>; reachStats: Record<string, number>; completionStats: Record<string, number>; hiringSpeed: Record<string, number>; slaStats: Record<string, number>; funnelData: Array<{ name: string; value: number }> };
export default function ReportsClient() {
  const [report, setReport] = useState<Report | null>(null); const [notice, setNotice] = useState('');
  useEffect(() => { fetch('/api/employer/analytics/dashboard?range=7d').then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error); return data; }).then(setReport).catch(e => setNotice(e.message)); }, []);
  const cards = report ? [['Active jobs', report.stats.activeJobs], ['Applications', report.stats.totalApplications], ['Impressions', report.reachStats.totalImpressions], ['Unique views', report.reachStats.uniqueViews], ['Completion', `${report.completionStats.completionRate}%`], ['Response rate', `${report.slaStats.responseRate}%`], ['Time to fill', `${report.hiringSpeed.avgTimeToFill} days`]] : [];
  return <section className="mx-auto max-w-6xl p-5 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#7b847e]">Work</p><h1 className="mt-2 text-3xl font-black">Reports</h1><p className="mt-2 text-[#6c756f]">Live seven-day hiring reach, conversion, and response monitoring.</p>{notice && <p className="mt-4 rounded-2xl bg-[#fff0c8] p-4 text-sm">{notice}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <div key={label} className="rounded-[24px] bg-white p-6"><p className="text-xs font-black uppercase tracking-wider text-[#747d77]">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div>)}</div>{report && <div className="mt-6 rounded-[28px] bg-white p-6"><h2 className="text-xl font-black">Hiring pipeline</h2><div className="mt-5 space-y-3">{report.funnelData.map(item => <div key={item.name} className="grid grid-cols-[100px_1fr_50px] items-center gap-3 text-sm"><span className="font-bold">{item.name}</span><span className="h-3 overflow-hidden rounded-full bg-[#eeebe4]"><span className="block h-full rounded-full bg-[#183d31]" style={{ width: `${report.funnelData[0]?.value ? Math.min(100, item.value / report.funnelData[0].value * 100) : 0}%` }} /></span><span className="text-right font-black">{item.value}</span></div>)}</div></div>}</section>;
}
