'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { BriefcaseBusiness, MapPin, Search, Sparkles } from 'lucide-react';
type Job = { id: string; title: string; description: string; location: string; location_type: string; company: { name: string }; applicationStatus: string | null; isInvited: boolean };
export default function FindWorkClient() {
  const [jobs, setJobs] = useState<Job[]>([]); const [query, setQuery] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { fetch('/api/professional/jobs/feed').then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }).then(data => setJobs(data.jobs ?? [])).catch(error => setNotice(error.message)); }, []);
  const matches = useMemo(() => jobs.filter(job => `${job.title} ${job.company?.name} ${job.location}`.toLowerCase().includes(query.toLowerCase())), [jobs, query]);
  return <section className="mx-auto max-w-6xl p-5 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#7b847e]">Opportunity</p><h1 className="mt-2 text-3xl font-black">Find work</h1><p className="mt-2 text-[#6c756f]">Roles ranked from your preferences, skills, location, activity, and application history.</p><label className="mt-7 flex gap-3 rounded-[24px] bg-white p-4 shadow-sm"><Search className="text-[#6c756f]" size={20} /><input value={query} onChange={event => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="Role, skill, or company" /></label>{notice && <p className="mt-4 rounded-2xl bg-[#fff0c8] p-4 text-sm">{notice}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2">{matches.map(job => <Link href={`/find-work/${job.id}`} key={job.id} className="rounded-[26px] bg-white p-6"><div className="flex justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e8efe9]"><BriefcaseBusiness size={19} /></span>{job.isInvited && <span className="flex items-center gap-1 rounded-full bg-[#fff0c8] px-3 py-1 text-xs font-black"><Sparkles size={13} /> Invited</span>}</div><h2 className="mt-6 text-xl font-black">{job.title}</h2><p className="mt-1 text-sm font-bold text-[#315548]">{job.company?.name}</p><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#6c756f]">{job.description}</p><div className="mt-4 flex justify-between text-xs font-bold text-[#747d77]"><span><MapPin size={14} className="mr-1 inline" />{job.location || job.location_type}</span><span>{job.applicationStatus || 'View role'}</span></div></Link>)}{!matches.length && <div className="rounded-[26px] bg-white p-10 text-center text-[#747d77] sm:col-span-2">No matching open roles.</div>}</div></section>;
}
