'use client';

import { useEffect, useState } from 'react';
import { CirclePlus, Clock, Trash2, X } from 'lucide-react';
type Update = { id: string; author_id: string; body: string; expires_at: string; created_at: string };
type Contact = { id: string; name: string };

export default function UpdatesClient() {
  const [updates, setUpdates] = useState<Update[]>([]); const [contacts, setContacts] = useState<Contact[]>([]); const [composer, setComposer] = useState(false); const [body, setBody] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [hours, setHours] = useState(24); const [notice, setNotice] = useState('');
  const load = () => fetch('/api/social/updates').then(r => r.json()).then(data => setUpdates(data.updates ?? []));
  useEffect(() => { load(); fetch('/api/social/contacts').then(r => r.json()).then(data => setContacts(data.contacts ?? [])); }, []);
  async function publish() { const response = await fetch('/api/social/updates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ body, audienceMode: 'selected', audienceIds: selected, durationHours: hours }) }); const data = await response.json(); if (!response.ok) return setNotice(data.error); setUpdates(current => [data.update, ...current]); setBody(''); setSelected([]); setComposer(false); }
  async function remove(id: string) { await fetch(`/api/social/updates?id=${id}`, { method: 'DELETE' }); setUpdates(current => current.filter(update => update.id !== id)); }
  return <section className="mx-auto max-w-5xl p-5 sm:p-8"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#7b847e]">Social</p><h1 className="mt-2 text-3xl font-black">Updates</h1><p className="mt-2 text-[#6c756f]">Private, timed updates for people you choose.</p></div><button onClick={() => setComposer(true)} className="flex items-center gap-2 rounded-2xl bg-[#183d31] px-4 py-3 text-sm font-bold text-white"><CirclePlus size={18} /> New update</button></div>{notice && <p className="mt-4 rounded-2xl bg-[#fff0c8] p-3 text-sm">{notice}</p>}<div className="mt-7 space-y-4">{updates.map(update => <article key={update.id} className="rounded-[28px] bg-white p-6"><p className="whitespace-pre-wrap leading-7">{update.body}</p><div className="mt-5 flex items-center justify-between text-xs text-[#747d77]"><span><Clock size={14} className="mr-1 inline" />Expires {new Date(update.expires_at).toLocaleString()}</span><button onClick={() => remove(update.id)} aria-label="Delete update"><Trash2 size={16} /></button></div></article>)}{!updates.length && <div className="rounded-[28px] bg-white p-10 text-center text-[#747d77]">No active updates.</div>}</div>{composer && <div className="fixed inset-0 z-50 grid place-items-center bg-[#17231d]/50 p-4"><div className="w-full max-w-lg rounded-[28px] bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">New update</h2><button onClick={() => setComposer(false)}><X /></button></div><textarea autoFocus value={body} onChange={e => setBody(e.target.value)} maxLength={4000} rows={6} className="mt-4 w-full rounded-2xl bg-[#f0eee8] p-4 outline-none" placeholder="What do you want to share?" /><p className="mt-4 text-xs font-black uppercase tracking-wider text-[#747d77]">Choose audience</p><div className="mt-2 max-h-44 overflow-y-auto">{contacts.map(contact => <label key={contact.id} className="flex items-center gap-3 rounded-xl p-2 hover:bg-[#f0eee8]"><input type="checkbox" checked={selected.includes(contact.id)} onChange={() => setSelected(current => current.includes(contact.id) ? current.filter(id => id !== contact.id) : [...current, contact.id])} />{contact.name}</label>)}{!contacts.length && <p className="py-4 text-sm text-[#747d77]">Approved contacts will appear here.</p>}</div><label className="mt-4 flex items-center justify-between text-sm font-bold">Visible for <select value={hours} onChange={e => setHours(Number(e.target.value))} className="rounded-xl bg-[#f0eee8] p-2"><option value={1}>1 hour</option><option value={24}>24 hours</option><option value={72}>3 days</option><option value={168}>7 days</option></select></label><button onClick={publish} disabled={!body.trim() || !selected.length} className="mt-5 w-full rounded-2xl bg-[#183d31] px-4 py-3 font-black text-white disabled:opacity-40">Publish privately</button></div></div>}</section>;
}
