'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Send } from 'lucide-react';
type Message = { id: string; sender_id: string; body: string; created_at: string };
export default function WorkChatClient({ conversationId }: { conversationId: string }) {
  const [messages, setMessages] = useState<Message[]>([]); const [viewerId, setViewerId] = useState(''); const [draft, setDraft] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { fetch(`/api/social/conversations/${conversationId}/messages`).then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error); return data; }).then(data => { setMessages(data.messages ?? []); setViewerId(data.viewerId ?? ''); }).catch(e => setNotice(e.message)); }, [conversationId]);
  async function send() { const body = draft.trim(); if (!body) return; setDraft(''); const response = await fetch(`/api/social/conversations/${conversationId}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ body }) }); const data = await response.json(); if (!response.ok) { setDraft(body); return setNotice(data.error); } setMessages(current => [...current, data.message]); }
  return <section className="flex h-[calc(100dvh-4rem)] flex-col"><header className="flex items-center gap-4 border-b border-[#18251f]/10 bg-white p-5"><Link href="/work" aria-label="Back to work groups"><ArrowLeft /></Link><div><h1 className="font-black">Work group</h1><p className="text-xs text-[#747d77]">Organisation-managed conversation</p></div></header>{notice && <p className="m-4 rounded-2xl bg-[#fff0c8] p-3 text-sm">{notice}</p>}<div className="flex-1 overflow-y-auto p-5 sm:p-8">{messages.map(message => <div key={message.id} className={`mb-3 flex ${message.sender_id === viewerId ? 'justify-end' : ''}`}><p className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm ${message.sender_id === viewerId ? 'rounded-br-md bg-[#183d31] text-white' : 'rounded-bl-md bg-white'}`}>{message.body}</p></div>)}</div><footer className="p-4"><div className="flex gap-3 rounded-2xl bg-white p-3"><textarea rows={1} value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }} className="flex-1 resize-none bg-transparent p-1 outline-none" placeholder="Message your team" /><button onClick={send} disabled={!draft.trim()} className="grid h-9 w-9 place-items-center rounded-xl bg-[#f6c85f] disabled:opacity-40"><Send size={17} /></button></div></footer></section>;
}
