'use client';
import { useEffect, useState } from 'react';
import { UserRound } from 'lucide-react';
type Application = { id: string; status: string; createdAt: string; job: { title: string }; user: { name: string }; isDm: boolean };
const statuses = ['pending', 'shortlisted', 'accepted', 'employed', 'rejected', 'declined', 'terminated'];
export default function ApplicationsClient() {
  const [applications, setApplications] = useState<Application[]>([]); const [notice, setNotice] = useState('');
  useEffect(() => { fetch('/api/employer/applications').then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error); return data; }).then(data => setApplications((data.applications ?? []).filter((item: Application) => !item.isDm))).catch(e => setNotice(e.message)); }, []);
  async function change(id: string, status: string) { const response = await fetch(`/api/employer/applications/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); const data = await response.json(); if (!response.ok) return setNotice(data.error || 'Status could not be changed.'); setApplications(current => current.map(item => item.id === id ? { ...item, status } : item)); setNotice(status === 'employed' ? 'Employment started and Ondwira workspace access was synchronized.' : status === 'terminated' ? 'Employment ended and workspace access was removed.' : 'Application updated.'); }
  return <section className="mx-auto max-w-6xl p-5 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#7b847e]">Work</p><h1 className="mt-2 text-3xl font-black">Applications</h1><p className="mt-2 text-[#6c756f]">Review candidates and move them through the real hiring lifecycle.</p>{notice && <p className="mt-4 rounded-2xl bg-[#fff0c8] p-4 text-sm">{notice}</p>}<div className="mt-6 space-y-3">{applications.map(application => <article key={application.id} className="flex flex-col gap-4 rounded-[24px] bg-white p-5 sm:flex-row sm:items-center"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e8efe9]"><UserRound size={19} /></span><div className="min-w-0 flex-1"><h2 className="font-black">{application.user.name}</h2><p className="text-sm text-[#6c756f]">{application.job.title} · applied {new Date(application.createdAt).toLocaleDateString()}</p></div><select value={application.status} onChange={e => change(application.id, e.target.value)} className="rounded-2xl bg-[#f0eee8] px-4 py-3 text-sm font-bold">{statuses.map(status => <option key={status}>{status}</option>)}</select></article>)}{!applications.length && <div className="rounded-[24px] bg-white p-10 text-center text-[#747d77]">No applications yet.</div>}</div></section>;
}
