export const COUNTRY_TO_CURRENCY: Record<string, string> = {
    // North America
    'united states': 'USD', 'usa': 'USD', 'us': 'USD', 'america': 'USD',
    'canada': 'CAD',
    'mexico': 'MXN',

    // Europe
    'united kingdom': 'GBP', 'uk': 'GBP', 'great britain': 'GBP', 'england': 'GBP', 'scotland': 'GBP', 'wales': 'GBP',
    'eurozone': 'EUR', 'europe': 'EUR',
    'germany': 'EUR', 'france': 'EUR', 'italy': 'EUR', 'spain': 'EUR', 'netherlands': 'EUR', 'belgium': 'EUR',
    'austria': 'EUR', 'ireland': 'EUR', 'finland': 'EUR', 'portugal': 'EUR', 'greece': 'EUR',
    'switzerland': 'CHF',
    'sweden': 'SEK',
    'norway': 'NOK',
    'denmark': 'DKK',
    'poland': 'PLN',
    'czech republic': 'CZK', 'czechia': 'CZK',
    'hungary': 'HUF',
    'romania': 'RON',
    'bulgaria': 'BGN',
    'croatia': 'EUR',
    'russia': 'RUB',
    'ukraine': 'UAH',
    'turkey': 'TRY', 'turkiye': 'TRY',

    // Asia
    'china': 'CNY',
    'japan': 'JPY',
    'india': 'INR',
    'south korea': 'KRW', 'korea': 'KRW',
    'indonesia': 'IDR',
    'vietnam': 'VND',
    'thailand': 'THB',
    'malaysia': 'MYR',
    'philippines': 'PHP',
    'singapore': 'SGD',
    'hong kong': 'HKD',
    'taiwan': 'TWD',
    'pakistan': 'PKR',
    'bangladesh': 'BDT',
    'sri lanka': 'LKR',
    'nepal': 'NPR',
    'saudi arabia': 'SAR',
    'uae': 'AED', 'united arab emirates': 'AED', 'dubai': 'AED',
    'israel': 'ILS',
    'qatar': 'QAR',
    'kuwait': 'KWD',
    'bahrain': 'BHD',
    'oman': 'OMR',
    'jordan': 'JOD',
    'lebanon': 'LBP',

    // Oceania
    'australia': 'AUD',
    'new zealand': 'NZD',

    // South America
    'brazil': 'BRL',
    'argentina': 'ARS',
    'colombia': 'COP',
    'chile': 'CLP',
    'peru': 'PEN',
    'venezuela': 'VES',
    'uruguay': 'UYU',
    'paraguay': 'PYG',
    'bolivia': 'BOB',

    // Africa
    'south africa': 'ZAR',
    'nigeria': 'NGN',
    'kenya': 'KES',
    'ghana': 'GHS',
    'egypt': 'EGP',
    'morocco': 'MAD',
    'algeria': 'DZD',
    'tunisia': 'TND',
    'ethiopia': 'ETB',
    'tanzania': 'TZS',
    'uganda': 'UGX',
    'rwanda': 'RWF',
    'zambia': 'ZMW',
    'zimbabwe': 'ZWL',
    'angola': 'AOA',
    'mozambique': 'MZN',
    'ivory coast': 'XOF', 'cote d\'ivoire': 'XOF',
    'senegal': 'XOF',
    'cameroon': 'XAF',
    'mauritius': 'MUR',

    // Others/Islands
    'iceland': 'ISK',
};

// Also map currency codes to symbols widely
export const CURRENCY_SYMBOLS: Record<string, string> = {
    USD: '$',
    EUR: '€',
    GBP: '£',
    JPY: '¥',
    CNY: '¥',
    INR: '₹',
    RUB: '₽',
    KRW: '₩',
    BRL: 'R$',
    TRY: '₺',
    IDR: 'Rp',
    ILS: '₪',
    SAR: '﷼',
    NGN: '₦',
    KES: 'KSh',
    GHS: '₵',
    ZAR: 'R',
    THB: '฿',
    VND: '₫',
    PHP: '₱',
    AUD: 'A$',
    CAD: 'C$',
    NZD: 'NZ$',
    HKD: 'HK$',
    SGD: 'S$',
    MXN: 'Mex$',
    TWD: 'NT$',
    MYR: 'RM',
    DKK: 'kr',
    SEK: 'kr',
    NOK: 'kr',
    PLN: 'zł',
    CZK: 'Kč',
    HUF: 'Ft',
    CHF: 'Fr',
    UAH: '₴',
    BDT: '৳',
    LKR: 'Rs',
    PKR: 'Rs',
    AED: 'dh',
    QAR: 'QR',
    MAD: 'DH',
    EGP: 'E£',
};
