'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { FileSignature, ShieldCheck } from 'lucide-react';
type Contract = { id: string; title: string; status: string; sent_at: string; organizations?: { name: string } };
type Signature = { id: string; label: string; is_default: boolean };
export default function ContractsClient() {
  const [contracts, setContracts] = useState<Contract[]>([]); const [signatures, setSignatures] = useState<Signature[]>([]); const [notice, setNotice] = useState('');
  const load = () => Promise.all([fetch('/api/work/contracts').then(r => r.json()), fetch('/api/settings/signatures').then(r => r.json())]).then(([contractData, signatureData]) => { setContracts(contractData.contracts ?? []); setSignatures(signatureData.signatures ?? []); });
  useEffect(() => { load().catch(() => setNotice('Contracts could not be loaded.')); }, []);
  async function sign(contractId: string) { const signature = signatures.find(item => item.is_default) || signatures[0]; if (!signature) return setNotice('Save a signature in Settings before signing.'); const response = await fetch('/api/work/contracts', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contractId, signatureId: signature.id }) }); const data = await response.json(); if (!response.ok) return setNotice(data.error); setNotice(data.status === 'signed' ? 'Contract fully signed.' : 'Your signature was added. Waiting for the other signer.'); await load(); }
  return <section className="mx-auto max-w-6xl p-5 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#7b847e]">Work</p><h1 className="mt-2 text-3xl font-black">Contracts</h1><p className="mt-2 text-[#6c756f]">Review and sign agreements using your saved normalized signature.</p>{notice && <p className="mt-4 rounded-2xl bg-[#fff0c8] p-4 text-sm">{notice}</p>}{!signatures.length && <Link href="/settings/documents" className="mt-5 inline-flex rounded-2xl bg-[#183d31] px-4 py-3 text-sm font-black text-white">Create a signature in Settings</Link>}<div className="mt-6 grid gap-4 sm:grid-cols-2">{contracts.map(contract => <article key={contract.id} className="rounded-[26px] bg-white p-6"><div className="flex justify-between"><FileSignature /><span className="rounded-full bg-[#e8efe9] px-3 py-1 text-xs font-black">{contract.status.replace('_', ' ')}</span></div><h2 className="mt-6 text-xl font-black">{contract.title || 'Employment contract'}</h2><p className="mt-1 text-sm text-[#6c756f]">{contract.organizations?.name || 'Organisation'} · sent {new Date(contract.sent_at).toLocaleDateString()}</p>{!['signed', 'voided', 'ended', 'declined'].includes(contract.status) && <button onClick={() => sign(contract.id)} className="mt-5 flex items-center gap-2 rounded-2xl bg-[#f6c85f] px-4 py-3 text-sm font-black"><ShieldCheck size={17} /> Sign with saved signature</button>}</article>)}{!contracts.length && <div className="rounded-[26px] bg-white p-10 text-center text-[#747d77] sm:col-span-2">No contracts have been sent yet.</div>}</div></section>;
}
