import Link from 'next/link';
import { Check, ChevronLeft, Coins, FileSearch, ShieldCheck, Sparkles } from 'lucide-react';

const items = [
  { icon: Coins, title: 'Applicant capacity', price: 'From KES 0.26 / extra person', body: 'Your first job with up to 20 application places is free. Larger capacity is charged per head, not per job.' },
  { icon: FileSearch, title: 'Document handling', price: 'Pay only for documents accepted', body: 'Set how many documents each applicant may attach. Every upload is inspected before release.' },
  { icon: Sparkles, title: 'Optional ATS AI', price: 'Metered by use', body: 'Choose the provider and model. Rank everyone, a percentage, or only candidates who meet your explicit criteria.' },
  { icon: ShieldCheck, title: 'Security inspection', price: 'Optional advanced scan', body: 'Basic validation is included. Advanced AI and malware analysis can be purchased per document.' },
];

export default function PricingPage() {
  return <main className="min-h-screen bg-[var(--bg-primary)] px-4 py-8 text-[var(--text-primary)] sm:px-7 sm:py-12"><div className="mx-auto max-w-6xl"><Link href="/" className="inline-flex items-center gap-2 font-mono text-xs font-black uppercase"><ChevronLeft size={15} /> Jobs</Link><div className="mt-9 grid gap-10 lg:grid-cols-[1fr_380px] lg:items-end"><div><p className="font-mono text-[10px] font-black uppercase tracking-[0.22em] text-[var(--accent-primary)]">Company pricing / Kenyan shillings only</p><h1 className="mt-4 text-[clamp(3.4rem,8vw,7rem)] font-black leading-[0.85] tracking-[-0.07em]">Pay for usage.<br />Not permission.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--text-secondary)]">Profcaria uses a prepaid wallet with optional auto top-up. There is no mandatory AI subscription and no charge just to keep a job page online.</p></div><aside className="border-2 border-[var(--text-primary)] bg-[var(--surface-raised)] p-6 shadow-[7px_7px_0_var(--accent-primary)]"><p className="font-mono text-[10px] font-black uppercase tracking-wider">Recommended billing model</p><p className="mt-4 text-3xl font-black">Hybrid pay-as-you-go</p><p className="mt-3 text-sm leading-6 text-[var(--text-secondary)]">One-time wallet top-ups for occasional employers, with optional monthly auto top-up and volume discounts for frequent hiring.</p></aside></div><div className="mt-14 grid gap-4 sm:grid-cols-2">{items.map(item => <article key={item.title} className="border-2 border-[var(--text-primary)] bg-[var(--surface-raised)] p-6"><item.icon className="text-[var(--accent-primary)]" /><h2 className="mt-8 text-2xl font-black">{item.title}</h2><p className="mt-2 font-mono text-xs font-black uppercase text-[var(--accent-primary)]">{item.price}</p><p className="mt-4 text-sm leading-6 text-[var(--text-secondary)]">{item.body}</p></article>)}</div><div className="mt-12 border-2 border-[var(--text-primary)] bg-[var(--text-primary)] p-7 text-[var(--bg-primary)] sm:p-10"><h2 className="text-3xl font-black">Always included</h2><div className="mt-6 grid gap-3 text-sm sm:grid-cols-2">{['Automatic closing at the application cap','Public machine-readable job page','Status email workflow','Company and job sharing links','Human review controls','Long-term audit history'].map(text => <p key={text} className="flex gap-2"><Check size={16} className="shrink-0 text-emerald-400" />{text}</p>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href="/employer/billing" className="inline-block border-2 border-[var(--bg-primary)] px-5 py-3 font-mono text-xs font-black uppercase">Open billing wallet</Link><Link href="/employer/home" className="inline-block border-2 border-[var(--bg-primary)] px-5 py-3 font-mono text-xs font-black uppercase">Company workspace</Link></div></div></div></main>;
}
